services:
  - type: web
    name: budgetwise-pro-backend
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /api/health
    autoDeploy: true
    branch: main

  - type: web
    name: budgetwise-pro-frontend
    env: static
    plan: starter
    buildCommand: npm install && npm run build
    staticPublishPath: .next
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true
    branch: main

databases:
  - name: budgetwise-pro-db
    databaseName: budgetwise_pro
    user: budgetwise_user
    plan: starter
